### ISSUE TITLE
Possible bug found in pom.xml

### ISSUE THREAD

**Issue by CharlesStockman** [springframeworkguru/kbe-rest-brewery#1]
Thanks for creating this repository.

After doing a git clone, I executed "mvn clean install" (  on two machines OSX and linux ) and the error message was the same for both ( shown below).
 
_Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project kbe-rest-brewery: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x1e56bc9b) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x1e56bc9b -> [Help 1]_

**The fix was to change org.lombok.version from 1.18.18 to 1.18.24** in the pom.xml file

**Comment by led93** [comment]
It is a bug reported originally in projectlombok/lombok#2681.
It seems to affect openjdk versions 16+.
Moving from from 1.18.18 to 1.18.24 solves the issue.

**Comment by CharlesStockman** [comment]
We have an answer to the issue
